<h1 style="text-align:center; border:2.5px solid #f248e4ff"> # Numpy </h1>

<b> Kyla Faith A. Pedrajas </b>
<br> Computer Engineer

In [1]:
# imports and packeges
import numpy as np

# 1D Array

In [2]:
my_array = [1, 2, 3]

In [3]:
type(my_array)

list

In [4]:
my_array = np.array([1, 2, 3])

In [5]:
type(my_array)

numpy.ndarray

In [10]:
np.shape(my_array)

(3,)

# 2D Array

In [28]:
syntax_array = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
])

In [29]:
syntax_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
syntax_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [31]:
np.shape(syntax_array)

(2, 5)

In [37]:
trans_array = syntax_array.T

In [38]:
syntax_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
np.shape(trans_array)

(5, 2)

In [14]:
resistance_test = np.array([
    ["Test #", "Jaguar", "Panther"],
    [1, 3, 9.1],
    [2, 9.1, 9.1],
    [3, 9.3, 9.1],
    [4, 9.5, 9.2],
])

resistance_test

array([['Test #', 'Jaguar', 'Panther'],
       ['1', '3', '9.1'],
       ['2', '9.1', '9.1'],
       ['3', '9.3', '9.1'],
       ['4', '9.5', '9.2']], dtype='<U32')

In [15]:
np.shape (resistance_test)

(5, 3)

In [16]:
resistance_test.T

array([['Test #', '1', '2', '3', '4'],
       ['Jaguar', '3', '9.1', '9.3', '9.5'],
       ['Panther', '9.1', '9.1', '9.1', '9.2']], dtype='<U32')

In [17]:
np.shape (resistance_test)

(5, 3)

In [19]:
resistance_test

array([['Test #', 'Jaguar', 'Panther'],
       ['1', '3', '9.1'],
       ['2', '9.1', '9.1'],
       ['3', '9.3', '9.1'],
       ['4', '9.5', '9.2']], dtype='<U32')

In [24]:
trans_array

array([['Test #', 'Jaguar', 'Panther'],
       ['1', '3', '9.1'],
       ['2', '9.1', '9.1'],
       ['3', '9.3', '9.1'],
       ['4', '9.5', '9.2']], dtype='<U32')

In [25]:
resistance_test

array([['Test #', 'Jaguar', 'Panther'],
       ['1', '3', '9.1'],
       ['2', '9.1', '9.1'],
       ['3', '9.3', '9.1'],
       ['4', '9.5', '9.2']], dtype='<U32')

In [26]:
np.shape(resistance_test)

(5, 3)

# Measures of Central Tendency

In [46]:
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8], #Jaguar
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan], #Panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [49]:
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])